
POST http://127.0.0.1:8181/links

{
    # "url": "http://127.0.0.1:8181/links/ASDasd"
    # "url": "http://127.0.0.1:8181/links/asdasd"
    # "url": "http://127.0.0.1:8181/links"
    "url": "aaa"
}


get http://127.0.0.1:8181/links/nA7GTPjpGh



get http://127.0.0.1:8181/links?offset=0&limit=10



delete http://127.0.0.1:8181/links/nA7GTPjpGh



get http://127.0.0.1:8181/links/nA7GTPjpGh/stats
